[package]
name = "webapp"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.44", features = ["serde"] }
dotenv = "0.15.0"
gloo-console = "0.3.0"
gloo-net = "0.6.0"
gloo-timers = "0.3.0"
serde = "1.0.228"
urlencoding = "2.1.3"
wasm-bindgen-futures = "0.4.58"
web-sys = "0.3.85"
yew = { version = "0.22", features = ["csr"] }
